# Generated by Django 5.2.1 on 2025-06-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='salary',
            new_name='score',
        ),
    ]
